name: sonarqube_${SONARQUBE_VERSION}
version: "3"
services:
  sonarqube:
    image: sonarqube:${SONARQUBE_VERSION}
    container_name: sonarqube_${SONARQUBE_VERSION}
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonarqube
    ports:
      - "9000:9000"
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: sonarqube-postgresql_${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarqube
networks:
  sonarqube:
    name: sonarqube
volumes:
  sonarqube_data:
    name: sonarqube_data
  sonarqube_extensions:
    name: sonarqube_extensions
  sonarqube_logs:
    name: sonarqube_logs
  postgresql:
    name: sonarqube-postgresql
  postgresql_data:
    name: sonarqube-postgresql_data